#!/bin/bash

set -ueo pipefail

LXC_SSHSETUP_PATH="$HOME/.ssh/lxc"

info() {
    printf "%s\n" "$*" >&2
}

fatal() {
    printf "%s\n" "$*" >&2
    exit 1
}

runlxc() {
    sudo lxc "$@"
}

fatal_usage() {
    fatal "usage: ${0##*/} [-p PORT] <instance>..."
}

names=()
port="22"

while [ "$#" -ne 0 ]; do
    case "$1" in
        "-p" | "--port")
            port="$2"
            shift
            ;;
        "-*")
            fatal_usage
            ;;
        *)
            names+=("$1")
            ;;
    esac
    shift
done

if [ "${#names[@]}" -eq 0 ]; then
    fatal_usage
fi

instances="$(runlxc list --format=json)"

setup() {
    name="$1"

    info "checking instance '${name}'..."
    query="map(select(.name == \"${name}\")) | first"
    info="$(jq "${query}" <<< "${instances}")" ||
    if [ "${info}" == "null" ]; then
        fatal "could not find instance '${name}'"
    fi

    status="$(jq -r ".status" <<< "${info}")"
    if [ ! "${status}" = "Running" ]; then
        fatal "instance '${name}' is not running"
    fi

    query='
        .state.network | map(.addresses) | flatten
        | map(select(.scope == "global" and .family == "inet")) | first.address
    '
    address="$(jq -r "${query}" <<< "${info}")"
    if [ "${address}" = "null" ]; then
        fatal "could not find reachable ipv4 address"
    fi

    key_file="${LXC_SSHSETUP_PATH}/${name}"
    pubkey_file="${key_file}.pub"
    config_file="${key_file}.config"

    if [ ! -f "${key_file}" ]; then
        info "generating public key pair for instance '${name}'..."
        dir="$(dirname "${key_file}")"
        mkdir -p "${dir}"
        chmod 700 "${dir}"
        ssh-keygen -t ed25519 -f "${key_file}" -N "" >&2
    fi

    script="$(cat <<"EOS"
set -ueo pipefail
KEYS_PATH="$HOME/.ssh/authorized_keys"
silent() {
    "$@" >/dev/null 2>&1
}
trap "echo ERROR" ERR
read key
if ! (silent grep -F "$key" "$KEYS_PATH"); then
    mkdir -p "$HOME/.ssh" && chmod 700 "$HOME/.ssh" && cat >> "$KEYS_PATH" <<< "$key"
fi
if ! (silent sshd -V); then
    echo "installing sshd..."
    if silent pacman -V; then
        pacman -Syu --noconfirm && pacman -S openssh --noconfirm
    elif silent apt-get -v; then
        apt-get update && apt-get install -y --no-install-recommends openssh-server
    else
        echo "could not find any supported package managers" >&2 && exit 1
    fi
fi
if (systemctl status ssh >/dev/null 2>&1); then
    systemctl enable ssh && systemctl start ssh
else
    systemctl enable sshd && systemctl start sshd
fi
EOS
    )"

    info "updating instance '${name}'..."
    decorate() {
        prefix=$'  > \e[2m'
        suffix=$'\e[m'
        sed -e "s/^/${prefix}/" -e "s/\$/${suffix}/"
    }
    runlxc exec "${name}" -- bash -c "${script}" 2>&1 < "${pubkey_file}" | decorate >&2

    info "writing ssh config to '${name}'..."
    cat > "${config_file}" <<EOS
Host ${name}
    HostName ${address}
    User root
    IdentityFile ${key_file}
    StrictHostKeyChecking no
    Port ${port}
EOS

    info "setup completed"
}

for name in "${names[@]}"; do
    setup "${name}"
done
